package app.enums;

public enum HANDLER_TYPE {
    login,
    register,
    close,
    getUserData,
    updateUserByPatient,
    getDoctorsList,
    getAvailableTime,
    setAppointment,
    getSchedule,
    sendComplaint,
    getPatientList,
    updateAppointmentDto,
    getPatientAppointment,
    getUserList,
    getCommentList,
    getDoctorsAndAppointmentCountDto,
    sendMail,
    deleteUser,
    deleteComment,
    getDistrictsForAdmin,
    getDoctorsForAdmin,
    updateDoctor,
    updateDistrict,
    addDistrict,
    addAddress,
    getReport,
    getAddressList,
    getUserAddress,
    updateUserAddress
}
